### Importing Libraries

In [1]:
import numpy as np

### Initial Weight Vectors

In [2]:
W1 = np.array([[0.5, 1.5, 0.8], [0.8, 0.2, -1.6]])
W2 = np.array([[0.9, -1.7, 1.6], [1.2, 2.1, -0.2]])

### Input and Output

In [3]:
X1 = np.array([1.0, 0.7, 1.2]) # input for layer 1
t = np.array([1.0, 0.0]) # target output    

### Activation Function

In [4]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

### Forward Propagation

In [5]:
def feed_forward_pass(X, W):
    return sigmoid(np.dot(W, X))

### Backward Propagation

In [6]:
def back_propagation(W, X, delta_vector, learning_rate):
    n, m = W.shape
    for j in range(n):
        for i in range(m):
            W[j, i] -= learning_rate * delta_vector[j] * X[i]
    return W

### Calculating Delta values for hidden layer

In [7]:
def calculate_delta_vector(W, delta_vector_k1, output):
    n, m = W.shape
    delta_vector = np.zeros(n)
    for j in range(n):
        for i in range(len(delta_vector_k1)):
            delta_vector[j] += delta_vector_k1[i] * W[i, j+1]
        delta_vector[j] *= output[j] * (1 - output[j])
    return delta_vector

### Multi Layer Perceptron

In [8]:
def multilayer_perceptron(X, W1, W2, t, learning_rate, epochs):
    for epoch in range(epochs):
        # feed forward
        output1 = feed_forward_pass(X, W1)
        X2 = np.array([1.0, *output1]) # input for layer 2
        output2 = feed_forward_pass(X2, W2)

        output = np.array([1 if x > 0.5 else 0 for x in output2])

        if np.array_equal(output, t):
            print(f"Converged after {epoch+1} epochs")
            break

        else:
            # back propagation
            delta2 = (output2 - t) * output2 * (1 - output2)
            W2 = back_propagation(W2, X2, delta2, learning_rate)

            delta1 = calculate_delta_vector(W2, delta2, output1)
            W1 = back_propagation(W1, X, delta1, learning_rate)
        
        print(f"Epoch {epoch+1}: {output}")
        print(f"W1: {W1}")
        print(f"W2: {W2}")

    return W1, W2



In [9]:
W1, W2 = multilayer_perceptron(X1, W1, W2, t, 0.5, 1000)

Epoch 1: [0 1]
W1: [[ 0.48928025  1.49249617  0.7871363 ]
 [ 0.8229341   0.21605387 -1.57247908]]
W2: [[ 0.96886855 -1.63630762  1.61879366]
 [ 1.18005027  2.08154969 -0.20544412]]
Epoch 2: [0 1]
W1: [[ 0.47892982  1.48525087  0.77471578]
 [ 0.84552115  0.2318648  -1.54537462]]
W2: [[ 1.03368231 -1.57650867  1.63735805]
 [ 1.15929163  2.0623972  -0.21138994]]
Epoch 3: [1 1]
W1: [[ 0.46899918  1.47829943  0.76279902]
 [ 0.86741089  0.24718763 -1.51910693]]
W2: [[ 1.09378691 -1.52118633  1.65539794]
 [ 1.13766631  2.04249252 -0.2178806 ]]
Epoch 4: [1 1]
W1: [[ 0.45949453  1.47164617  0.75139344]
 [ 0.88835515  0.2618486  -1.49397382]]
W2: [[ 1.14890458 -1.47057303  1.672693  ]
 [ 1.11511214  2.02178153 -0.22495775]]
Epoch 5: [1 1]
W1: [[ 0.45038709  1.46527096  0.7404645 ]
 [ 0.90821357  0.2757495  -1.47014372]]
W2: [[ 1.19907099 -1.42461242  1.68910477]
 [ 1.09156163  2.00020543 -0.23266222]]
Epoch 6: [1 1]
W1: [[ 0.4416251   1.45913757  0.72995012]
 [ 0.92693896  0.28885727 -1.44767325

In [10]:
print(f"Final W1: {W1}")
print(f"Final W2: {W2}")

Final W1: [[ 0.20679927  1.29475949  0.44815912]
 [ 1.29043107  0.54330175 -1.01148271]]
Final W2: [[ 1.68827945 -0.98697397  1.89770305]
 [-0.20463444  0.86477494 -0.87138284]]
